user:
  name: "Moncef Belyamani"
  email: "git@rubyonmac.dev"

# Possible values are: atom, bbedit, brackets, emacs, nano, sublime, textmate, vim, vscode
# Let me know if your favorite editor is missing.
editor: "sublime"
