#!/bin/bash

source ./functions/logging.sh

info_echo "Running your customizations from ~/rubyonmac/rom-custom ..."

brewfiles=( "$HOME/rubyonmac/Brewfile-rom-custom" "$HOME/Brewfile.local" "$HOME/Brewfile" )
for brewfile in "${brewfiles[@]}"; do
  if [ -f "$brewfile" ]; then
    info_echo "Installing tools and apps from $brewfile ..."
    if brew bundle --no-lock --file="$brewfile"; then
      success_echo "All items in $brewfile were installed successfully."
    else
      error_echo "Some items in $brewfile were not installed successfully."
    fi
  fi
done

info_echo "Copying ruby packer binaries ..."

cp "$HOME/Documents/Business/Ruby\ on\ Mac/ruby_packer/arm64/rubyc" "/opt/homebrew/bin/rubyc"
cp "$HOME/Documents/Business/Ruby\ on\ Mac/ruby_packer/i386/rubyc" "/usr/local/bin/rubyc"
