#!/bin/bash

source ./functions/logging.sh

info_echo "Running your customizations from ~/rubyonmac/rom-custom ..."

brewfiles=( "$HOME/rubyonmac/Brewfile-rom-custom" "$HOME/Brewfile.local" "$HOME/Brewfile" )
for brewfile in "${brewfiles[@]}"; do
  if [ -f "$brewfile" ]; then
    info_echo "Installing tools and apps from $brewfile ..."
    if brew bundle --no-lock --file="$brewfile"; then
      success_echo "All items in $brewfile were installed successfully."
    else
      error_echo "Some items in $brewfile were not installed successfully."
    fi
  fi
done

if [ -f "$HOME/Documents/Business/Ruby on Mac/ruby_packer/arm64/rubyc" ] && [ ! -f "/opt/homebrew/bin/rubyc" ]; then
  info_echo "Copying arm64 ruby packer binary ..."
  cp "$HOME/Documents/Business/Ruby on Mac/ruby_packer/arm64/rubyc" "/opt/homebrew/bin/rubyc"
  chmod 755 /opt/homebrew/bin/rubyc
fi

if [ -f "$HOME/Documents/Business/Ruby on Mac/ruby_packer/i386/rubyc" ] && [ ! -f "/usr/local/bin/rubyc" ]; then
  info_echo "Copying i386 ruby packer binary ..."
  cp "$HOME/Documents/Business/Ruby on Mac/ruby_packer/i386/rubyc" "/usr/local/bin/rubyc"
  chmod 755 /usr/local/bin/rubyc
fi
